### ISSUE TITLE
Gallery didn't pick up my new notebook

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-gallery/pangeo-gallery#12]
Seems like my github actions are working for the ESIP 02_ notebook
https://github.com/rsignell-usgs/esip-gallery/actions
https://github.com/rsignell-usgs/esip-gallery/actions/runs/82062363
but it didn't seem to get picked up in the gallery (or maybe I just have to wait for it?)
![2020-04-19_9-11-18](https://user-images.githubusercontent.com/1872600/79688673-c3de2700-821d-11ea-8864-2ca252997278.png)

**Comment by rabernat** [comment]
The sphinx build for your notebook failed:
https://github.com/pangeo-gallery/pangeo-gallery/runs/599335771?check_suite_focus=true#step:7:25

I can reproduce this locally when I run `make html`. The full error log is:
```
# Sphinx version: 2.4.4
# Python version: 3.8.1 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 12 source files that are out of date
#   updating environment:
#   1 added, 6 changed, 0 removed
#   reading sources... [ 14%] index
#   reading sources... [ 28%] repos/NCAR/cesm-lens-aws/index
#   reading sources... [ 42%] repos/pangeo-gallery/example-gallery/index
#   reading sources... [ 57%] repos/pangeo-gallery/physical-oceanography/index
#   reading sources... [ 71%] repos/rsignell-usgs/esip-gallery/01_hurricane_ike_water_levels
#   reading sources... [ 85%] repos/rsignell-usgs/esip-gallery/02_National_Water_Model
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/alabaster/__init__.py
#   nbsphinx (0.5.1) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/nbsphinx.py
#   sphinxcontrib.fulltoc (unknown version) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinxcontrib/fulltoc.py
#   sphinx_pangeo_theme (unknown version) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx_pangeo_theme/__init__.py
#   sphinx_bootstrap_theme (unknown version) from /Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx_bootstrap_theme/__init__.py
Traceback (most recent call last):
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/io.py", line 129, in read
    self.input = self.read_source(settings.env)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/io.py", line 139, in read_source
    env.events.emit('source-read', env.docname, arg)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/Users/rpa/pangeo-gallery/pangeo-gallery/conf.py", line 197, in rstjinja
    rendered = app.builder.templates.render_string(
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/sphinx/jinja2glue.py", line 195, in render_string
    return self.environment.from_string(source).render(context)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/rpa/opt/miniconda3/envs/pangeo-py38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 3635, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'F'.
```

This is ultimately probably an nbsphinx error. Something in that notebook is causing problems when nbsphinx, something related to jinja templates.
